language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
notifications:
  email:
    recipients:
      - mrdaniel19996@gmail.com
    on_success: always
    on_failure: always
